#!/usr/bin/env bash

echo $FILE
for i in {1..10}; do
    NEW_UUID=$(openssl rand -base64 6)
    FILE="${NEW_UUID}.txt"
    echo $FILE
    dd if=/dev/urandom of=$FILE bs=1k count=1

done
echo "done adding file ..... "
git add .
git commit -am "added some files ... with hash $RANDOM"
git push 
echo "code comit "
find ./ -maxdepth 1 -type f -name "*.txt" -print0 | \
        head -n 1 | xargs -0 rm
echo "removing old files ..."
git add .
git commit -am "removed some files -- hash $RANDOM"
git push 
echo "Process complete ..."
