name: CI

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: add git config 1
      run: git config --global user.email "sarkar.anurag@oyorooms.com"
    - name:  add git config 1
      run: git config --global user.name "anuragsarkar97"
    - name: Run script
      run: sh cron
